// Code generated by godddx, DO AVOID EDIT.
package event

import "context"

// Storer data persistence
type Storer interface {
	Event() EventStorer
}

// Dispatcher 告警事件分发接口，解耦 push 包与 event 包，避免循环依赖
type Dispatcher interface {
	Dispatch(ctx context.Context, ev *Event)
}

// Core business domain
type Core struct {
	store    Storer
	notifier Dispatcher
}

// NewCore create business domain
func NewCore(store Storer) Core {
	return Core{store: store}
}

// SetNotifier 注入 webhook 推送器，nil 表示不推送
func (c *Core) SetNotifier(d Dispatcher) {
	c.notifier = d
}

// AddEventAndNotify 入库成功后触发 webhook 推送，供 AI 回调 API 层使用
// 与生成的 AddEvent 分离，保证生成文件不被污染
func (c Core) AddEventAndNotify(ctx context.Context, in *AddEventInput) (*Event, error) {
	out, err := c.AddEvent(ctx, in)
	if err != nil {
		return nil, err
	}
	if c.notifier != nil {
		c.notifier.Dispatch(ctx, out)
	}
	return out, nil
}
