// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: protos/analysis.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1 // 服务正常
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2 // 服务不可用 (加载模型中)
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_analysis_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_protos_analysis_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{9, 0}
}

// 启动摄像头分析请求
type StartCameraRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// === 基础信息 ===
	CameraId   string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`       // 摄像头唯一标识 (必填)
	CameraName string `protobuf:"bytes,2,opt,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"` // 摄像头名称，用于日志 (可选)
	RtspUrl    string `protobuf:"bytes,3,opt,name=rtsp_url,json=rtspUrl,proto3" json:"rtsp_url,omitempty"`          // RTSP 子码流地址 (必填)
	// === 检测配置 ===
	DetectIntervalSeconds float32  `protobuf:"fixed32,4,opt,name=detect_interval_seconds,json=detectIntervalSeconds,proto3" json:"detect_interval_seconds,omitempty"` // 分析间隔（秒），默认 2.0，支持小数（如 0.5 表示每秒 2 帧）
	Labels                []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`                                                                // 要检测的标签，如 ["person", "car"]，空则检测全部
	Threshold             float32  `protobuf:"fixed32,6,opt,name=threshold,proto3" json:"threshold,omitempty"`                                                        // 置信度阈值，默认 0.5
	// === ROI 区域 (多边形点位) ===
	// n 个坐标组合成的多边形，例如 [0.1, 0.2, 0.12, 0.22, 0.1, 0.3...]
	// 归一化坐标 (x1, y1, x2, y2, ...)
	RoiPoints []float32 `protobuf:"fixed32,7,rep,packed,name=roi_points,json=roiPoints,proto3" json:"roi_points,omitempty"`
	// 错误处理
	RetryLimit int32 `protobuf:"varint,8,opt,name=retry_limit,json=retryLimit,proto3" json:"retry_limit,omitempty"` // 遇到错误的自动重试次数，默认 10
	// === 回调配置 ===
	// 优先级高于服务启动时的默认配置
	CallbackUrl    string `protobuf:"bytes,10,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`          // HTTP 回调地址 (必填)
	CallbackSecret string `protobuf:"bytes,11,opt,name=callback_secret,json=callbackSecret,proto3" json:"callback_secret,omitempty"` // 回调签名密钥 (可选，用于验证)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartCameraRequest) Reset() {
	*x = StartCameraRequest{}
	mi := &file_protos_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCameraRequest) ProtoMessage() {}

func (x *StartCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCameraRequest.ProtoReflect.Descriptor instead.
func (*StartCameraRequest) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *StartCameraRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *StartCameraRequest) GetCameraName() string {
	if x != nil {
		return x.CameraName
	}
	return ""
}

func (x *StartCameraRequest) GetRtspUrl() string {
	if x != nil {
		return x.RtspUrl
	}
	return ""
}

func (x *StartCameraRequest) GetDetectIntervalSeconds() float32 {
	if x != nil {
		return x.DetectIntervalSeconds
	}
	return 0
}

func (x *StartCameraRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StartCameraRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartCameraRequest) GetRoiPoints() []float32 {
	if x != nil {
		return x.RoiPoints
	}
	return nil
}

func (x *StartCameraRequest) GetRetryLimit() int32 {
	if x != nil {
		return x.RetryLimit
	}
	return 0
}

func (x *StartCameraRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *StartCameraRequest) GetCallbackSecret() string {
	if x != nil {
		return x.CallbackSecret
	}
	return ""
}

type StartCameraResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 流信息 (通过 ffprobe 探测返回)
	SourceWidth   int32   `protobuf:"varint,3,opt,name=source_width,json=sourceWidth,proto3" json:"source_width,omitempty"`    // 原始分辨率宽度
	SourceHeight  int32   `protobuf:"varint,4,opt,name=source_height,json=sourceHeight,proto3" json:"source_height,omitempty"` // 原始分辨率高度
	SourceFps     float32 `protobuf:"fixed32,5,opt,name=source_fps,json=sourceFps,proto3" json:"source_fps,omitempty"`         // 原始帧率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCameraResponse) Reset() {
	*x = StartCameraResponse{}
	mi := &file_protos_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCameraResponse) ProtoMessage() {}

func (x *StartCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCameraResponse.ProtoReflect.Descriptor instead.
func (*StartCameraResponse) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *StartCameraResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartCameraResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartCameraResponse) GetSourceWidth() int32 {
	if x != nil {
		return x.SourceWidth
	}
	return 0
}

func (x *StartCameraResponse) GetSourceHeight() int32 {
	if x != nil {
		return x.SourceHeight
	}
	return 0
}

func (x *StartCameraResponse) GetSourceFps() float32 {
	if x != nil {
		return x.SourceFps
	}
	return 0
}

type StopCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCameraRequest) Reset() {
	*x = StopCameraRequest{}
	mi := &file_protos_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCameraRequest) ProtoMessage() {}

func (x *StopCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCameraRequest.ProtoReflect.Descriptor instead.
func (*StopCameraRequest) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *StopCameraRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type StopCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCameraResponse) Reset() {
	*x = StopCameraResponse{}
	mi := &file_protos_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCameraResponse) ProtoMessage() {}

func (x *StopCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCameraResponse.ProtoReflect.Descriptor instead.
func (*StopCameraResponse) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *StopCameraResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopCameraResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_protos_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"` // AI 模型是否加载完成
	Cameras       []*CameraStatus        `protobuf:"bytes,2,rep,name=cameras,proto3" json:"cameras,omitempty"`                 // 摄像头状态列表
	Stats         *GlobalStats           `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`                     // 全局统计信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_protos_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *StatusResponse) GetCameras() []*CameraStatus {
	if x != nil {
		return x.Cameras
	}
	return nil
}

func (x *StatusResponse) GetStats() *GlobalStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CameraStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CameraId        string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                           // "running", "error", "stopped"
	FramesProcessed int64                  `protobuf:"varint,3,opt,name=frames_processed,json=framesProcessed,proto3" json:"frames_processed,omitempty"` // 已处理帧数
	LastError       string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`                    // 最后一次错误信息
	RetryCount      int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`                // 当前重试次数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CameraStatus) Reset() {
	*x = CameraStatus{}
	mi := &file_protos_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraStatus) ProtoMessage() {}

func (x *CameraStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraStatus.ProtoReflect.Descriptor instead.
func (*CameraStatus) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *CameraStatus) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CameraStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CameraStatus) GetFramesProcessed() int64 {
	if x != nil {
		return x.FramesProcessed
	}
	return 0
}

func (x *CameraStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *CameraStatus) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type GlobalStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActiveStreams   int32                  `protobuf:"varint,1,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`       // 当前活跃 RTSP 流数量
	TotalDetections int64                  `protobuf:"varint,2,opt,name=total_detections,json=totalDetections,proto3" json:"total_detections,omitempty"` // 服务启动以来的总检测次数
	UptimeSeconds   int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`       // 运行时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GlobalStats) Reset() {
	*x = GlobalStats{}
	mi := &file_protos_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStats) ProtoMessage() {}

func (x *GlobalStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStats.ProtoReflect.Descriptor instead.
func (*GlobalStats) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalStats) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *GlobalStats) GetTotalDetections() int64 {
	if x != nil {
		return x.TotalDetections
	}
	return 0
}

func (x *GlobalStats) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_protos_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{8}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=analysis.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_protos_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_protos_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_protos_analysis_proto protoreflect.FileDescriptor

const file_protos_analysis_proto_rawDesc = "" +
	"\n" +
	"\x15protos/analysis.proto\x12\banalysis\"\xe7\x02\n" +
	"\x12StartCameraRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x1f\n" +
	"\vcamera_name\x18\x02 \x01(\tR\n" +
	"cameraName\x12\x19\n" +
	"\brtsp_url\x18\x03 \x01(\tR\artspUrl\x126\n" +
	"\x17detect_interval_seconds\x18\x04 \x01(\x02R\x15detectIntervalSeconds\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\x12\x1c\n" +
	"\tthreshold\x18\x06 \x01(\x02R\tthreshold\x12\x1d\n" +
	"\n" +
	"roi_points\x18\a \x03(\x02R\troiPoints\x12\x1f\n" +
	"\vretry_limit\x18\b \x01(\x05R\n" +
	"retryLimit\x12!\n" +
	"\fcallback_url\x18\n" +
	" \x01(\tR\vcallbackUrl\x12'\n" +
	"\x0fcallback_secret\x18\v \x01(\tR\x0ecallbackSecret\"\xb0\x01\n" +
	"\x13StartCameraResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fsource_width\x18\x03 \x01(\x05R\vsourceWidth\x12#\n" +
	"\rsource_height\x18\x04 \x01(\x05R\fsourceHeight\x12\x1d\n" +
	"\n" +
	"source_fps\x18\x05 \x01(\x02R\tsourceFps\"0\n" +
	"\x11StopCameraRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"H\n" +
	"\x12StopCameraResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\x8a\x01\n" +
	"\x0eStatusResponse\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady\x120\n" +
	"\acameras\x18\x02 \x03(\v2\x16.analysis.CameraStatusR\acameras\x12+\n" +
	"\x05stats\x18\x03 \x01(\v2\x15.analysis.GlobalStatsR\x05stats\"\xae\x01\n" +
	"\fCameraStatus\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10frames_processed\x18\x03 \x01(\x03R\x0fframesProcessed\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\"\x86\x01\n" +
	"\vGlobalStats\x12%\n" +
	"\x0eactive_streams\x18\x01 \x01(\x05R\ractiveStreams\x12)\n" +
	"\x10total_detections\x18\x02 \x01(\x03R\x0ftotalDetections\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x14\n" +
	"\x12HealthCheckRequest\"\x96\x01\n" +
	"\x13HealthCheckResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.analysis.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xe6\x01\n" +
	"\x0fAnalysisService\x12J\n" +
	"\vStartCamera\x12\x1c.analysis.StartCameraRequest\x1a\x1d.analysis.StartCameraResponse\x12G\n" +
	"\n" +
	"StopCamera\x12\x1b.analysis.StopCameraRequest\x1a\x1c.analysis.StopCameraResponse\x12>\n" +
	"\tGetStatus\x12\x17.analysis.StatusRequest\x1a\x18.analysis.StatusResponse2N\n" +
	"\x06Health\x12D\n" +
	"\x05Check\x12\x1c.analysis.HealthCheckRequest\x1a\x1d.analysis.HealthCheckResponseB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_protos_analysis_proto_rawDescOnce sync.Once
	file_protos_analysis_proto_rawDescData []byte
)

func file_protos_analysis_proto_rawDescGZIP() []byte {
	file_protos_analysis_proto_rawDescOnce.Do(func() {
		file_protos_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_analysis_proto_rawDesc), len(file_protos_analysis_proto_rawDesc)))
	})
	return file_protos_analysis_proto_rawDescData
}

var file_protos_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_analysis_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: analysis.HealthCheckResponse.ServingStatus
	(*StartCameraRequest)(nil),             // 1: analysis.StartCameraRequest
	(*StartCameraResponse)(nil),            // 2: analysis.StartCameraResponse
	(*StopCameraRequest)(nil),              // 3: analysis.StopCameraRequest
	(*StopCameraResponse)(nil),             // 4: analysis.StopCameraResponse
	(*StatusRequest)(nil),                  // 5: analysis.StatusRequest
	(*StatusResponse)(nil),                 // 6: analysis.StatusResponse
	(*CameraStatus)(nil),                   // 7: analysis.CameraStatus
	(*GlobalStats)(nil),                    // 8: analysis.GlobalStats
	(*HealthCheckRequest)(nil),             // 9: analysis.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 10: analysis.HealthCheckResponse
}
var file_protos_analysis_proto_depIdxs = []int32{
	7,  // 0: analysis.StatusResponse.cameras:type_name -> analysis.CameraStatus
	8,  // 1: analysis.StatusResponse.stats:type_name -> analysis.GlobalStats
	0,  // 2: analysis.HealthCheckResponse.status:type_name -> analysis.HealthCheckResponse.ServingStatus
	1,  // 3: analysis.AnalysisService.StartCamera:input_type -> analysis.StartCameraRequest
	3,  // 4: analysis.AnalysisService.StopCamera:input_type -> analysis.StopCameraRequest
	5,  // 5: analysis.AnalysisService.GetStatus:input_type -> analysis.StatusRequest
	9,  // 6: analysis.Health.Check:input_type -> analysis.HealthCheckRequest
	2,  // 7: analysis.AnalysisService.StartCamera:output_type -> analysis.StartCameraResponse
	4,  // 8: analysis.AnalysisService.StopCamera:output_type -> analysis.StopCameraResponse
	6,  // 9: analysis.AnalysisService.GetStatus:output_type -> analysis.StatusResponse
	10, // 10: analysis.Health.Check:output_type -> analysis.HealthCheckResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_analysis_proto_init() }
func file_protos_analysis_proto_init() {
	if File_protos_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_analysis_proto_rawDesc), len(file_protos_analysis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protos_analysis_proto_goTypes,
		DependencyIndexes: file_protos_analysis_proto_depIdxs,
		EnumInfos:         file_protos_analysis_proto_enumTypes,
		MessageInfos:      file_protos_analysis_proto_msgTypes,
	}.Build()
	File_protos_analysis_proto = out.File
	file_protos_analysis_proto_goTypes = nil
	file_protos_analysis_proto_depIdxs = nil
}
