// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"fmt"
	"strings"

	"github.com/gowvp/owl/internal/core/bz"
	"github.com/ixugo/goddd/pkg/orm"
)

// Device domain model
type Device struct {
	ID   string `gorm:"primaryKey" json:"id"`
	Type string `gorm:"column:type;notNull;default:'GB28181';comment:设备类型(onvif)" json:"type"` // 设备类型(onvif/gb28181)

	// 自定义 id 可以简写为 did，国标 device_id 应简写成 gbid，而不是 device_id
	// 起这个名义会难以区分，但为了兼容已经部署的旧数据库...保留
	DeviceID string `gorm:"column:device_id;notNull;uniqueIndex;default:'';comment:20 位国标编号" json:"device_id"` // 20 位国标编号

	// 自定义名称
	Name         string    `gorm:"column:name;notNull;default:'';comment:设备名称" json:"name"`                                                    // 设备名称
	Transport    string    `gorm:"column:transport;notNull;default:'';comment:传输协议(tcp/udp)" json:"transport"`                                 // 传输协议(TCP/UDP)
	StreamMode   int8      `gorm:"column:stream_mode;notNull;default:1;comment:数据传输模式(0:UDP; 1:TCP_PASSIVE; 2:TCP_ACTIVE)" json:"stream_mode"` // 数据传输模式
	IP           string    `gorm:"column:ip;notNull;default:''" json:"ip"`
	Port         int       `gorm:"column:port;notNull;default:0" json:"port"`
	IsOnline     bool      `gorm:"column:is_online;notNull;default:FALSE" json:"is_online"`
	RegisteredAt orm.Time  `gorm:"column:registered_at;notNull;default:CURRENT_TIMESTAMP;comment:注册时间" json:"registered_at"` // 注册时间
	KeepaliveAt  orm.Time  `gorm:"column:keepalive_at;notNull;default:CURRENT_TIMESTAMP;comment:心跳时间" json:"keepalive_at"`   // 心跳时间
	Keepalives   int       `gorm:"column:keepalives;notNull;default:0;comment:心跳间隔" json:"keepalives"`                       // 心跳间隔
	Expires      int       `gorm:"column:expires;notNull;default:0;comment:注册有效期" json:"expires"`                            // 注册有效期
	Channels     int       `gorm:"column:channels;notNull;default:0;comment:通道数量" json:"channels"`                           // 通道数量
	CreatedAt    orm.Time  `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`       // 创建时间
	UpdatedAt    orm.Time  `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`       // 更新时间
	Password     string    `gorm:"column:password;notNull;default:'';comment:注册密码" json:"password"`
	Address      string    `gorm:"column:address;notNull;default:'';comment:设备网络地址" json:"address"`
	Ext          DeviceExt `gorm:"column:ext;notNull;default:'{}';type:jsonb;comment:设备属性" json:"ext"` // 设备属性
	Username     string    `gorm:"column:username;notNull;default:'';comment:用户名" json:"username"`

	Children []*Channel `gorm:"-" json:"children,omitzero"`
}

func (d *Device) IsOnvif() bool {
	return strings.HasPrefix(d.ID, bz.IDPrefixOnvif) || d.Type == TypeOnvif
}

func (d *Device) IsGB28181() bool {
	return strings.HasPrefix(d.ID, bz.IDPrefixGB) || d.Type == TypeGB28181 || d.Type == ""
}

// TableName database table name
func (*Device) TableName() string {
	return "devices"
}

func (d Device) Check() error {
	if d.IsGB28181() && len(d.Username) < 18 {
		return fmt.Errorf("国标 ID 长度应大于等于 18 位")
	}
	if d.IsOnvif() {
		if d.Username == "" {
			return fmt.Errorf("用户名不能为空")
		}
		if d.Password == "" {
			return fmt.Errorf("密码不能为空")
		}
		if d.IP == "" {
			return fmt.Errorf("IP不能为空")
		}
		if d.Port == 0 {
			return fmt.Errorf("端口不能为空")
		}
	}
	return nil
}

func (d *Device) init(id, gbid string) {
	d.ID = id
	d.DeviceID = gbid
}

func (d *Device) NetworkAddress() string {
	return d.Transport + "://" + d.Address
}

// 实现 port.Device 接口
func (d *Device) GetID() string {
	return d.ID
}

func (d *Device) GetName() string {
	if d.Name != "" {
		return d.Name
	}
	if d.Ext.Name != "" {
		return d.Ext.Name
	}
	if d.DeviceID != "" {
		return d.DeviceID
	}
	return d.ID
}

func (d *Device) GetGB28181DeviceID() string {
	// if d.Username != "" {
	// return d.Username
	// }
	return d.DeviceID
}

func (d *Device) GetType() string {
	if d.Type != "" {
		return d.Type
	}
	return GetType(d.ID)
}

func (d *Device) GetIP() string {
	return d.IP
}

func (d *Device) GetPort() int {
	return d.Port
}

func (d *Device) GetUsername() string {
	return d.Username
}

func (d *Device) GetPassword() string {
	return d.Password
}
